/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir_toko_selekta;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Wawan
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * Creates new form frm_supplier1
     */
    public frm_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Data Master");

        jMenuItem1.setText("Karyawan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Barang");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Supplier");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem5.setText("Transaksi");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(580, 467));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new frm_karyawan().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new frm_barang().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new frm_supplier().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
//        new frm_struk_belanja().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    //============================== LOGIN
//    private Dimension dmn = Toolkit.getDefaultToolkit().getScreenSize();
//    public frm_utama(String userlogin) {
//
//        initComponents();
//        String _User = userlogin;
//        
//      
//        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
//        switch (_User) {
//            case "Administrator":
//                loginAdmin();
//                break;
//            case "User 1":
//                loginUser1();
//                break;
//            case "User 2":
//                loginUser1();
//                break;
//            case "User 3":
//                loginUser1();
//                break;
//            case "User 4":
//                loginUser1();
//                break;
//            case "User 5":
//                loginUser1();
//                break;
//            case "User 6":
//                loginUser1();
//                break;
//            case "User 7":
//                loginUser1();
//                break;
//            case "User 8":
//                loginUser1();
//                break;
//            case "User 9":
//                loginUser1();
//                break;
//            
//        }
//    }
//
//    frm_utama() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
//    
//    
//    public void loginAdmin(){
//        jMenu2.setVisible(true);
//        jMenuItem1.setEnabled(true);
//        jMenuItem2.setEnabled(true);
//          
//    }
//    
//    public void loginUser1(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    
//    public void loginUser2(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    public void loginUser3(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    public void loginUser4(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    public void loginUser5(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    public void loginUser6(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    public void loginUser7(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    public void loginUser8(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    public void loginUser9(){
//        jMenuItem1.setEnabled(false);
//        jMenuItem2.setEnabled(false);
//        
//    }
//    
    
    
    //=================================
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
